name: Stub tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    name: Go ${{ matrix.go-version }} - ${{ matrix.os }}/${{ matrix.test-arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        test-arch: [amd64]
        race: ["-race"]

        include:
          - go-version: 1.20.x
            test-arch: "386"
            os: ubuntu-latest
            race: ""
          - go-version: 1.20.x
            test-arch: "386"
            os: windows-latest
            race: ""

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests on stubs
        shell: bash
        env:
          GOARCH: ${{ matrix.test-arch }}
        run: |
          ./bin/run-tests test-stubs
